añadí el archivo index de las estadisticas

diff --git a/.github/workflows/jekyll-gh-pages.yml b/.github/workflows/jekyll-gh-pages.yml
--- a/.github/workflows/jekyll-gh-pages.yml
+++ b/.github/workflows/jekyll-gh-pages.yml
@@ -58,7 +58,7 @@ jobs:
           git add ./cliente/stats.json
           if ! git diff --cached --quiet || [ "${{ env.exists }}" = "false" ]; then
             git commit -m "Actualización automática del archivo JSON"
-            git push origin main
+            git push origin main || { echo "Error al hacer push"; exit 1; }
           else
             echo "No hay cambios en el archivo JSON, no se realizará un commit."
           fi
@@ -70,4 +70,4 @@ jobs:
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./estadisticas # Reemplaza con la ruta donde está el contenido que quieres publicar
+          publish_dir: ./estadisticas
